### ISSUE TITLE
Flow routing fails to build with fresh install of meteor 1.6

### ISSUE THREAD

**Issue by nethoncho** [meteor-useraccounts/flow-routing#56]
I am not sure if this an issue with the bundled version of npm or not.  My steps to reproduce are:
Create Ubuntu 10.04.3 x64 DigitalOcean droplet with 2GB of ram
```
apt-get update
apt-get upgrade
curl https://install.meteor.com/ | sh
adduser meteor
su - meteor
meteor --version
```
Meteor 1.6
```
meteor create --bare testApp
cd testApp
meteor
```
=> App running at: http://localhost:3000/
```
^C
meteor add useraccounts:flow-routing
```
=> Errors while adding packages:
/home/meteor/.npm/_logs/2017-11-07T05_18_16_760Z-debug.log
```
cat /home/meteor/.npm/_logs/2017-11-07T05_18_16_760Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node',
1 verbose cli   '/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm',
1 verbose cli   'rebuild',
1 verbose cli   '--update-binary' ]
2 info using npm@5.4.2
3 info using node@v8.8.1
4 info readInstalled object
5 verbose rebuild path, id [ '/tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/phantomjs',
5 verbose rebuild   'phantomjs@1.9.16' ]
6 silly rebuild set [ '/tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/phantomjs' ]
7 info build /tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/phantomjs
8 info lifecycle phantomjs@1.9.16~preinstall: phantomjs@1.9.16
9 info linkStuff phantomjs@1.9.16
10 silly linkStuff phantomjs@1.9.16 has /tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules as its parent node_modules
11 verbose linkBins phantomjs@1.9.16
12 verbose linkBins [ { phantomjs: './bin/phantomjs' },
12 verbose linkBins   '/tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/.bin',
12 verbose linkBins   false ]
13 verbose linkMans phantomjs@1.9.16
14 verbose rebuildBundles phantomjs@1.9.16
15 info lifecycle phantomjs@1.9.16~install: phantomjs@1.9.16
16 verbose lifecycle phantomjs@1.9.16~install: unsafe-perm in lifecycle true
17 verbose lifecycle phantomjs@1.9.16~install: PATH: /home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/bin/node-gyp-bin:/tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/phantomjs/node_modules/.bin:/tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/.bin:/tmp/mt-hal3np.06ywl/npm/node_modules/.bin:/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin:/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/.bin:/home/meteor/bin:/home/meteor/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
18 verbose lifecycle phantomjs@1.9.16~install: CWD: /tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6/node_modules/phantomjs
19 silly lifecycle phantomjs@1.9.16~install: Args: [ '-c', 'node install.js' ]
20 silly lifecycle phantomjs@1.9.16~install: Returned: code: 1  signal: null
21 info lifecycle phantomjs@1.9.16~install: Failed to exec install script
22 verbose stack Error: phantomjs@1.9.16 install: `node install.js`
22 verbose stack Exit status 1
22 verbose stack     at EventEmitter.<anonymous> (/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
22 verbose stack     at emitTwo (events.js:125:13)
22 verbose stack     at EventEmitter.emit (events.js:213:7)
22 verbose stack     at ChildProcess.<anonymous> (/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
22 verbose stack     at emitTwo (events.js:125:13)
22 verbose stack     at ChildProcess.emit (events.js:213:7)
22 verbose stack     at maybeClose (internal/child_process.js:927:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
23 verbose pkgid phantomjs@1.9.16
24 verbose cwd /tmp/mt-hal3np.06ywl/npm/node_modules/.temp-efogol.u8b6
25 verbose Linux 4.4.0-97-generic
26 verbose argv "/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/node" "/home/meteor/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin/npm" "rebuild" "--update-binary"
27 verbose node v8.8.1
28 verbose npm  v5.4.2
29 error code ELIFECYCLE
30 error errno 1
31 error phantomjs@1.9.16 install: `node install.js`
31 error Exit status 1
32 error Failed at the phantomjs@1.9.16 install script.
32 error This is probably not a problem with npm. There is likely additional logging output above.
33 verbose exit [ 1, true ]
```

**Comment by nethoncho** [comment]
I believe this is an issue with dependencies not being resolved. I added kadira:flow-router then useraccounts:flow-routing built with out any issues.
